# This is a basic workflow to help you get started with Actions

name: github-checkout

# Controls when the workflow will run
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run pwd
        run: pwd
      - name: Run ls -al
        run: ls -al
          
